name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Runs every 5 minutes.
  # Runs at 00:00 UTC every day.
  # Actions schedules run at most every 5 minutes.
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      id: debian-pyenv
      uses: docker/build-push-action@v3
      with:
        context: /home/runner/work/docker-amd64-custom-ubuntu-topfreeproxies/docker-amd64-custom-ubuntu-topfreeproxies
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/custom-ubuntu-topfreeproxies:latest
        platforms: linux/amd64

    - name: Run Docker Image
      run: |
        docker run --platform linux/amd64 -v '/home/runner/work/docker-amd64-custom-ubuntu-topfreeproxies/docker-amd64-custom-ubuntu-topfreeproxies/debian.backup:/debian.backup' ${{ secrets.DOCKER_USERNAME }}/custom-ubuntu-topfreeproxies:latest
  
    - name: 'Get Date'
      run: |
        echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add .
        git commit -m "${{env.REPORT_DATE}} 提交"
        git pull --rebase
        
    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: master
        force: true
